-- Создание таблицы пациентов
CREATE TABLE IF NOT EXISTS patients (
    id BIGINT generated by default as identity  PRIMARY KEY ,
    owner_name VARCHAR(255) NOT NULL,
    pet_name VARCHAR(255) NOT NULL,
    species VARCHAR(255) NOT NULL,
    breed VARCHAR(255) NOT NULL,
    date_of_birth DATE NOT NULL,
    notes VARCHAR(500)
);

-- Создание таблицы записей к врачу
CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT generated by default as identity PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    doctor_name VARCHAR(255) NOT NULL,
    appointment_date_time TIMESTAMP NOT NULL,
    reason VARCHAR(1000),
    notes VARCHAR(1000),
    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE
);

-- Создание таблицы медицинских карточек
CREATE TABLE IF NOT EXISTS medical_records (
    id BIGINT generated by default as identity PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    record_date TIMESTAMP NOT NULL,
    diagnosis VARCHAR(500) NOT NULL,
    symptoms VARCHAR(2000),
    treatment VARCHAR(2000),
    prescriptions VARCHAR(2000),
    notes VARCHAR(1000),
    doctor_name VARCHAR(255) NOT NULL,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE
);
